Repository srinidh-007/HackotberFest2021, pull requests merged in 2021-10, with the labels that each got.

#1 Create welcome.html
  welcome.html
Labels: good first issue

#6 InteractiveStudentRecords.c
  InteractiveStudentRecords.c
Labels: good first issue

#25 Add Longest Palindromic Substring
  LongestPalindromicSubstring.cpp
Labels: hackotberfest-accepted

#69 changed contributing.md
  contribute.md
Labels: good first issue, good
